### ISSUE TITLE
Import CSV Dateien nicht mehr möglich

### ISSUE THREAD

**Issue by patricknitsch** [solectrus/senec-importer#35]
Hallo, 
nach dem Update auf 0.10.1 wollte ich statistische csv-Daten einspielen. Nach Ausführung des Befehls kommt folgende Fehlermeldung: 

docker: env file .env contains invalid utf8 bytes at line 72: [83 69 78 69 67 95 73 78 84 69 82 86 65 76 61 50 226].See 'docker run --help'. 

Vor dem Update hat der Befehl funktioniert. Gibt es hier Probleme mit der .env Datei? 

Viele Grüße

**Comment by patricknitsch** [comment]
Zeile 72 ist leer.

Die Bearbeitung war bisher nur über die Konsole mittels nano

**Comment by ledermann** [comment]
ChatGPT meint: 


> The sequence "83 69 78 69 67 95 73 78 84 69 82 86 65 76 61 50 226" represents a series of decimal values for individual bytes. To make sense of this sequence, you can convert these decimal values into their corresponding ASCII or UTF-8 characters.
>
> Here's the conversion of the decimal values to ASCII characters:
>
>83 -> S
>69 -> E
>78 -> N
>69 -> E
>67 -> C
>95 -> _
>73 -> I
>78 -> N
>84 -> T
>69 -> E
>82 -> R
>86 -> V
>65 -> A
>76 -> L
>61 -> =
>50 -> 2
>226 -> â (This is a valid UTF-8 character, but it might be incorrectly placed or misinterpreted in the context of the .env file)
>
>So, the sequence of characters represented by these decimal values is:
>
>SENEC_INTE_RVAL=2â
>
>It's likely that the last character (â) is causing the problem. Check your ".env" file, specifically line 72, and correct or remove the invalid character as needed.

Schau Dir mal die Zeile mit `SENEC_INTERVAL` an, ob die irgendwie komisch aussieht. Nimm die Zeile notfalls mal heraus. Fürs Importieren wird sie nicht gebraucht.

**Comment by patricknitsch** [comment]
Das war es. Nach der Zahl für den Intervall war noch eine Leerstelle. 

Danke für deine schnelle Unterstützung. Super Tool!
