### ISSUE TITLE
senec importer lädt meine historischen Original-senec-Daten nicht

### ISSUE THREAD

**Issue by GuenniAC** [solectrus/senec-importer#4]
Hallo Georg,
vorab: die Installation war super-easy. Es lief auf Anhieb. Kompliment für diese tolle Arbeit.

Ich habe SOLECTRUS lokal auf einem debian bullseye system installiert. Dabei habe ich .env angepasst aber alle Passwörter auf default gelassen. 
Ich kann das Dashboard unter Port 3000 erreichen. Daten werden alle 10 sec gesammelt. Nach Modifikation von docker-compose.yml kann ich mich auch in influxdb anmelden.

root@sau:/home/guenni/solectrus# nmap -sT sau
Starting Nmap 7.80 ( https://nmap.org ) at 2023-01-30 13:01 CET
Nmap scan report for sau (127.0.1.1)
Host is up (0.00012s latency).
Other addresses for sau (not scanned): 192.168.11.8
Not shown: 981 closed ports
PORT     STATE SERVICE
...
3000/tcp open  ppp
8086/tcp open  d-s-n
...

Jetzt zum Problem: Der Import von senec-Daten funktioniert leider nicht.

```
root@sau:/home/guenni/solectrus# docker run -it --rm --env-file /data/senec/senec-importer-main/.env --env INFLUX_HOST=192.168.11.8 ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2022 Georg Ledermann, released under the MIT License

Using Ruby 3.1.3 on platform x86_64-linux-musl
Pushing to InfluxDB at http://192.168.11.8:8086, bucket my-solectrus-bucket

Importing data from /data/senec/senec-Web-Statistik-Original/raw-data ...
Imported 0 files


root@sau:/home/guenni/solectrus# ls -l /data/senec/senec-Web-Statistik-Original/raw-data
insgesamt 428
-rw-r--r-- 1 guenni guenni 143006 10. Jan 19:23 S30147251446072327540227639-week-1-2023.csv
-rw-r--r-- 1 guenni guenni 146435 16. Jan 19:30 S30147251446072327540227639-week-2-2023.csv
-rw-r--r-- 1 guenni guenni 147199 27. Jan 11:51 S30147251446072327540227639-week-3-2023.csv
root@sau:/home/guenni/solectrus# 
```
Kannst du mir helfen?
Was kann ich testen?

Danke.
Günter

**Comment by GuenniAC** [comment]
Kaum habe ich das geschrieben komme ich nicht mehr aufs dashboard:

`root@sau:/home/guenni/solectrus# docker ps -f health=unhealthy
CONTAINER ID   IMAGE                                COMMAND               CREATED          STATUS                      PORTS                                       NAMES
77574092c556   ghcr.io/solectrus/solectrus:latest   "docker/startup.sh"   33 minutes ago   Up 15 minutes (**unhealthy**)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   solectrus-app-1
root@sau:/home/guenni/solectrus# docker restart 77574092c556
77574092c556
root@sau:/home/guenni/solectrus# docker ps -f health=unhealthy
CONTAINER ID   IMAGE                                COMMAND               CREATED             STATUS                      PORTS                                       NAMES
77574092c556   ghcr.io/solectrus/solectrus:latest   "docker/startup.sh"   About an hour ago   Up 43 minutes (**unhealthy**)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   solectrus-app-1
root@sau:/home/guenni/solectrus# 
`
Auszug aus syslog:
`root@sau:/var/log# tail -f syslog|grep -i docker
Jan 30 14:16:09 sau systemd[1]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.B1PPXc.mount: Succeeded.
Jan 30 14:16:09 sau systemd[2671263]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.B1PPXc.mount: Succeeded.
Jan 30 14:16:48 sau dockerd[1361846]: time="2023-01-30T14:16:48.088605434+01:00" level=info msg="Container failed to exit within 10s of signal 15 - using the force" container=77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372
Jan 30 14:16:48 sau systemd[1]: docker-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372.scope: Succeeded.
Jan 30 14:16:48 sau systemd[1]: docker-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372.scope: Consumed 4.025s CPU time.
Jan 30 14:16:48 sau dockerd[1361846]: time="2023-01-30T14:16:48.172467131+01:00" level=info msg="ignoring event" container=77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 30 14:16:48 sau systemd[1783]: run-docker-netns-0a9ee033f7bf.mount: Succeeded.
Jan 30 14:16:48 sau systemd[2671263]: run-docker-netns-0a9ee033f7bf.mount: Succeeded.
Jan 30 14:16:48 sau systemd[1]: run-docker-netns-0a9ee033f7bf.mount: Succeeded.
Jan 30 14:16:48 sau systemd[1783]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.TD48ap.mount: Succeeded.
Jan 30 14:16:48 sau systemd[2671263]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.TD48ap.mount: Succeeded.
Jan 30 14:17:18 sau systemd[2671263]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.yKpDXO.mount: Succeeded.
Jan 30 14:17:18 sau systemd[1]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.yKpDXO.mount: Succeeded.
Jan 30 14:17:18 sau systemd[1783]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.yKpDXO.mount: Succeeded.
Jan 30 14:17:48 sau systemd[2671263]: run-docker-runtime\x2drunc-moby-77574092c556c1fee00117538a8de3f3690f10635b6f0d0a9546bbfccfdf4372-runc.ALW6qm.mount: Succeeded.
`
Auf die Datenbank komme ich und der Collector läuft:
`#group,false,false,true,true,false,false,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string
#default,mean,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement
,,0,2023-01-30T12:52:09.109513401Z,2023-01-30T13:52:09.109513401Z,2023-01-30T12:52:20Z,2.6,bat_charge_current,SENEC
,,0,2023-01-30T12:52:09.109513401Z,2023-01-30T13:52:09.109513401Z,2023-01-30T12:52:30Z,2.4,bat_charge_current,SENEC
,,0,2023-01-30T12:52:09.109513401Z,2023-01-30T13:52:09.109513401Z,2023-01-30T12:52:40Z,2.1,bat_charge_current,SENEC
,,0,2023-01-30T12:52:09.109513401Z,2023-01-30T13:52:09.109513401Z,2023-01-30T12:52:50Z,2.3,bat_charge_current,SENEC
`
Was nun? 
Neu installieren?

**Comment by ledermann** [comment]
Zum ersten Problem (Import): Ich vermute, es liegt am nicht angegebenen Docker-Volume, die CSV-Dateien werden nicht gefunden. Versuche es mal hiermit:

```bash
docker run -it --rm \
           --env-file /data/senec/senec-importer-main/.env \
           --env INFLUX_HOST=192.168.11.8 \
           -v /data/senec/senec-Web-Statistik-Original/raw-data:/data ghcr.io/solectrus/senec-importer
```

Auf den Host-Ordner `/data/senec/senec-Web-Statistik-Original/raw-data` kann dann vom Container aus zugegriffen werden, dort heißt er dann `/data`.

**Comment by GuenniAC** [comment]
Bingo! Ich hatte den Sinn hinter -v ...:/data nicht verstanden!
Danke schön!
